# application.yml
spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password:



